### ISSUE TITLE
issue w/ posting a RAMONSynapse with no segments 

### ISSUE THREAD

**Issue by alexbaden** [openconnectome/ndio#185]
| ndio version | os | python |
| --- | --- | --- |
| 1.0.0 | X | 2.7 |

```
Traceback (most recent call last):
  File "collman15ramon.py", line 37, in <module>
    main()
  File "collman15ramon.py", line 32, in main
    nd.post_ramon(token, channel, robj)
  File "/Users/abaden/.virtualenvs/ocp/lib/python2.7/site-packages/ndio/remote/neurodata.py", line 77, in wrapped
    return f(self, *args, **kwargs)
  File "/Users/abaden/.virtualenvs/ocp/lib/python2.7/site-packages/ndio/remote/neurodata.py", line 1037, in post_ramon
    tmpfile = ramon.to_hdf5(i, tmpfile)
  File "/Users/abaden/.virtualenvs/ocp/lib/python2.7/site-packages/ndio/ramon/__init__.py", line 419, in to_hdf5
    data=numpy.asarray(ramon.segments, dtype=numpy.uint32))
  File "/Users/abaden/.virtualenvs/ocp/lib/python2.7/site-packages/numpy/core/numeric.py", line 462, in asarray
    return array(a, dtype, copy=False, order=order)
TypeError: long() argument must be a string or a number, not 'NoneType'
```

w/ `robj = ndramon.RAMONSynapse(segments=None)`

**Comment by Aeusman** [comment]
Code to replicate? or should I close?
