### ISSUE TITLE
global name 'getURL' is not defined

### ISSUE THREAD

**Issue by kkutten1** [openconnectome/ndio#264]
| ndio version |  os  | python |
|-----|------|-------|
| 1.1.6  | Ubuntu 14.04    | 2.7.6     |

**Steps to reproduce**
```
import ndio.remote.neurodata as neurodata 
nd = neurodata("", server="https://mri.neurodata.io/ns/sd/")
nd.get_proj_info("<MyToken>")
```
**Expected behavior**
Dictionary with project information is returned

**Actual behavior**
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/cis/home/kwame/.local/lib/python2.7/site-packages/ndio/remote/neurodata.py", line 99, in wrapped
    return f(self, *args, **kwargs)
  File "/cis/home/kwame/.local/lib/python2.7/site-packages/ndio/remote/neurodata.py", line 235, in get_proj_info
    r = getURL(self.url() + "{}/info/".format(token))`
```

**Comment by Aeusman** [comment]
Fixing in #265

**Comment by Aeusman** [comment]
Pending a roll of pypi, but this is fixed
